/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleContent: typeof import('./src/components/article/ArticleContent.vue')['default']
    ArticleHero: typeof import('./src/components/article/ArticleHero.vue')['default']
    ArticleTOC: typeof import('./src/components/article/ArticleTOC.vue')['default']
    AuthContainer: typeof import('./src/components/common/auth/AuthContainer.vue')['default']
    BackToTop: typeof import('./src/components/common/BackToTop.vue')['default']
    CommentInput: typeof import('./src/components/article/comment/CommentInput.vue')['default']
    CommentList: typeof import('./src/components/article/comment/CommentList.vue')['default']
    CommentSection: typeof import('./src/components/article/CommentSection.vue')['default']
    FeaturedCursor: typeof import('./src/components/featured/FeaturedCursor.vue')['default']
    FeaturedList: typeof import('./src/components/featured/FeaturedList.vue')['default']
    FeaturedSpotlight: typeof import('./src/components/featured/FeaturedSpotlight.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    LoginForm: typeof import('./src/components/common/auth/LoginForm.vue')['default']
    LoginModal: typeof import('./src/components/common/LoginModal.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTime: typeof import('naive-ui')['NTime']
    PostCard: typeof import('./src/components/common/PostCard.vue')['default']
    PostEditor: typeof import('./src/components/admin/post/PostEditor.vue')['default']
    PostList: typeof import('./src/components/admin/post/PostList.vue')['default']
    RegisterForm: typeof import('./src/components/common/auth/RegisterForm.vue')['default']
    ResetForm: typeof import('./src/components/common/auth/ResetForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/search/SearchInput.vue')['default']
    SearchOverlay: typeof import('./src/components/common/SearchOverlay.vue')['default']
    SearchResultItem: typeof import('./src/components/search/SearchResultItem.vue')['default']
    SearchResults: typeof import('./src/components/search/SearchResults.vue')['default']
    SettingsDrawer: typeof import('./src/components/common/SettingsDrawer.vue')['default']
    SkeletonCard: typeof import('./src/components/common/SkeletonCard.vue')['default']
  }
}
